#!/bin/bash

# Получаем состояние батареи
state=$(cat /sys/class/power_supply/BAT*/status)

# Проверяем состояние и выводим истину или ложь
if [[ "$state" == "Discharging" ]]; then
    echo false
else
    echo true
fi
