#!/bin/sh

# Получаем результат команды и сохраняем в переменной
mute_status=$(pactl get-source-mute @DEFAULT_SOURCE@ | awk '{print $2}')

# Сравниваем результат с "yes"
if [ "$mute_status" = "yes" ]; then
    echo "./image/no mic.png"  # Возвращаем 1, если звук выключен
else
    echo "./image/mic.png"  # Возвращаем 0, если звук включен
fi
